import { Images, Plus } from "lucide-react";
import { submitBannerStatus, submitCreateBanner, submitDeleteBanner } from "@/app/admin-actions";
import { Card, EmptyState, Notice, SectionHeading, StatusBadge } from "@/components/ui";
import { Pagination } from "@/components/pagination";
import { ImageUploadField } from "@/components/image-upload-field";
import { can } from "@/lib/auth/permissions";
import { requirePermission } from "@/lib/auth/guard";
import { listBanners } from "@/lib/db/repositories/catalog";
import { formatDate } from "@/lib/utils/format";

export const dynamic = "force-dynamic";

export default async function BannersPage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string; page?: string }> }) {
  const scope = await requirePermission("banners.read"); const { error, success, page: rawPage } = await searchParams; const page = Math.max(1, Number.parseInt(rawPage ?? "1", 10) || 1); const rows = await listBanners(page); const banners = rows.slice(0, 25); const manage = can(scope.account.role, "banners.manage");
  return <><SectionHeading title="Banners" description="Upload banner artwork and choose a fixed in-app destination. The app displays only the artwork—no title or subtitle overlay." action={manage ? <a className="primary-button" href="#new-banner"><Plus size={16} />New banner</a> : undefined} />{success ? <Notice type="success">{success}</Notice> : null}{error ? <Notice type="error">{error}</Notice> : null}
    {manage ? <Card className="create-panel"><details id="new-banner"><summary><span><Images size={18} /><b>Create scheduled banner</b></span><small>Recommended 1200 × 450 px · JPG, PNG or WebP · maximum 2 MB.</small></summary><form action={submitCreateBanner} className="admin-form" encType="multipart/form-data"><div className="form-grid"><label>Placement<select name="placement" required defaultValue="HOME"><option>HOME</option><option>ROOM</option><option>WALLET</option><option>PROFILE</option></select></label><ImageUploadField name="image" label="Upload banner image" hint="Drag/drop or choose · 1200 × 450 px · maximum 2 MB" required /><label>Tap action<select name="actionType" defaultValue="NONE"><option value="NONE">No action</option><option value="LIVE">Face Live</option><option value="PARTY">Party Live</option><option value="PROFILE">Profile</option><option value="AGENCY">Agency</option><option value="WALLET">Wallet</option><option value="DAILY_REWARD">Daily reward</option><option value="RANKING">Ranking</option></select></label><label>Target ID (optional)<input name="actionTarget" inputMode="numeric" maxLength={80} /></label><label>Starts<input name="startsAt" type="datetime-local" /></label><label>Ends<input name="endsAt" type="datetime-local" /></label><label>Priority<input name="priority" type="number" min="0" max="999" defaultValue="0" required /></label><label className="checkbox-line"><input name="enabled" type="checkbox" value="true" defaultChecked />Enabled immediately</label></div><div className="form-submit"><p>The server automatically converts every upload to optimized WebP.</p><button className="primary-button" type="submit">Create banner</button></div></form></details></Card> : null}
    <Card>{banners.length ? <div className="table-scroll"><table><thead><tr><th>Artwork</th><th>Placement</th><th>Action</th><th>Schedule</th><th>Priority</th><th>Status</th>{manage ? <th>Action</th> : null}</tr></thead><tbody>{banners.map((banner) => <tr key={banner.id}><td data-label="Artwork"><b className="block">{banner.title}</b><a className="table-link" href={banner.imageUrl} target="_blank" rel="noreferrer">View WebP</a></td><td data-label="Placement">{banner.placement}</td><td data-label="Action">{banner.actionType}</td><td data-label="Schedule">{formatDate(banner.startsAt)} → {formatDate(banner.endsAt)}</td><td data-label="Priority">{banner.priority}</td><td data-label="Status"><StatusBadge value={banner.active ? "ACTIVE" : "DISABLED"} /></td>{manage ? <td data-label="Manage"><form action={submitBannerStatus}><input type="hidden" name="id" value={banner.id} /><input type="hidden" name="active" value={String(!banner.active)} /><button className="table-link button-link" type="submit">{banner.active ? "Disable" : "Enable"}</button></form><details className="row-action"><summary>Delete banner</summary><form action={submitDeleteBanner} className="stack-form"><input type="hidden" name="id" value={banner.id} /><p>Remove this banner from all placements. Audit history is kept.</p><input name="reason" required minLength={5} maxLength={500} placeholder="Why is it unused?" /><input name="confirmation" required pattern="DELETE" placeholder="Type DELETE" aria-label="Type DELETE to confirm banner deletion" /><button className="danger-button" type="submit">Delete permanently</button></form></details></td> : null}</tr>)}</tbody></table></div> : <EmptyState title="No banners configured" detail="Create the first scheduled banner for the mobile app." />}<Pagination path="/dashboard/banners" page={page} hasNext={rows.length > 25} /></Card>
  </>;
}
