import { Coins, PackagePlus, Store } from "lucide-react";
import { submitCoinOrderTransition, submitCoinPackageStatus, submitCoinPackageUpdate, submitCreateCoinPackage, submitSellerProfile } from "@/app/admin-actions";
import { Pagination } from "@/components/pagination";
import { Card, EmptyState, Notice, SectionHeading, StatusBadge } from "@/components/ui";
import { can } from "@/lib/auth/permissions";
import { requirePermission } from "@/lib/auth/guard";
import { listCoinCommerce } from "@/lib/db/repositories/mobile-administration";
import { formatDate, formatNumber } from "@/lib/utils/format";

export const dynamic = "force-dynamic";

function nextOrderStatuses(status: string) {
  if (status === "PENDING_CONTACT") return ["PAYMENT_PENDING", "SELLER_REVIEWING", "REJECTED", "CANCELLED"];
  if (status === "PAYMENT_PENDING") return ["SELLER_REVIEWING", "REJECTED", "CANCELLED"];
  if (status === "SELLER_REVIEWING") return ["COMPLETED", "REJECTED", "CANCELLED"];
  return [];
}

export default async function CommercePage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string; page?: string }> }) {
  const scope = await requirePermission("coin_orders.read");
  const { error, success, page: rawPage } = await searchParams;
  const page = Math.max(1, Number.parseInt(rawPage ?? "1", 10) || 1);
  const rows = await listCoinCommerce(scope, page);
  const commerce = { ...rows, orders: rows.orders.slice(0, 25) };
  const manageOrders = can(scope.account.role, "coin_orders.manage");
  const managePackages = can(scope.account.role, "coin_packages.manage");
  const manageSellers = can(scope.account.role, "sellers.manage");
  return <>
    <SectionHeading title="Coin commerce" description="Approved WhatsApp sellers create contact requests here; only a reviewed server transaction can move coin inventory." />
    {success ? <Notice type="success">{success}</Notice> : null}{error ? <Notice type="error">{error}</Notice> : null}
    {managePackages ? <Card className="create-panel"><details><summary><span><PackagePlus size={18} /><b>Create coin package</b></span><small>Published packages appear in the mobile wallet.</small></summary><form action={submitCreateCoinPackage} className="admin-form"><div className="form-grid"><label>Name<input name="name" required maxLength={100} placeholder="Starter coins" /></label><label>Badge<input name="badge" maxLength={40} placeholder="Popular" /></label><label>Coins<input name="coins" type="number" min="1" required /></label><label>Display price<input name="price" type="number" min="0" step="0.01" /></label><label>Currency<input name="currency" minLength={3} maxLength={3} placeholder="INR" /></label><label>Sort order<input name="sortOrder" type="number" min="0" max="999" defaultValue="0" required /></label><label>Confirm<button className="primary-button" type="submit">Create package</button></label></div></form></details></Card> : null}
    <Card><div className="card-title"><div><h2>Packages</h2><p>Coin amounts are snapshotted into every order. Package edits are audited.</p></div><Coins size={20} /></div>{commerce.packages.length ? <div className="table-scroll"><table><thead><tr><th>Public ID</th><th>Name / badge</th><th className="align-right">Coins</th><th>Display price</th><th>Status</th>{managePackages ? <th>Action</th> : null}</tr></thead><tbody>{commerce.packages.map((item) => <tr key={item.id}><td className="mono">{item.publicId}</td><td><b>{item.name}</b><small className="block">{item.badge ?? "No badge"}</small></td><td className="align-right">{formatNumber(item.coins)}</td><td>{item.price == null ? "Contact seller" : `${item.currency ?? ""} ${item.price.toLocaleString()}`}</td><td><StatusBadge value={item.active ? "ACTIVE" : "DISABLED"} /></td>{managePackages ? <td><details><summary className="table-link">Edit</summary><form action={submitCoinPackageUpdate} className="inline-review"><input type="hidden" name="packageId" value={item.id} /><input name="name" required maxLength={100} defaultValue={item.name} /><input name="badge" maxLength={40} defaultValue={item.badge ?? ""} placeholder="Badge" /><input name="coins" type="number" min="1" required defaultValue={item.coins} /><input name="price" type="number" min="0" step="0.01" defaultValue={item.price ?? 0} /><input name="currency" minLength={3} maxLength={3} required defaultValue={item.currency ?? "INR"} /><input name="sortOrder" type="number" min="0" max="999" required defaultValue={item.sortOrder} /><input name="reason" minLength={5} maxLength={500} required placeholder="Change reason" /><button className="table-button" type="submit">Save</button></form></details><form action={submitCoinPackageStatus}><input type="hidden" name="packageId" value={item.id} /><input type="hidden" name="active" value={String(!item.active)} /><button type="submit" className="table-link button-link">{item.active ? "Disable" : "Enable"}</button></form></td> : null}</tr>)}</tbody></table></div> : <EmptyState title="No coin packages" detail="Create a package before approving sellers for mobile sales." />}</Card>
    {manageSellers ? <><div className="section-subheading"><h2>Approved sellers</h2><p>WhatsApp is exposed to the app only when the seller is verified, available, public, and assigned an active package.</p></div>{commerce.sellers.length ? <div className="report-grid">{commerce.sellers.map((seller) => <Card key={seller.id}><div className="card-title"><div><h2>{seller.name}</h2><p>{seller.role.replaceAll("_", " ")} · ID {seller.publicId}</p></div><Store size={20} /></div><form action={submitSellerProfile} className="stack-form full-width"><input type="hidden" name="sellerId" value={seller.id} /><label>Verification<select name="verification" defaultValue={seller.verification}><option>UNVERIFIED</option><option>PENDING</option><option>VERIFIED</option><option>REJECTED</option></select></label><label>Business WhatsApp (E.164)<input name="whatsapp" defaultValue={seller.whatsapp ?? ""} placeholder="+919876543210" /></label><div className="two-fields"><label>Availability<select name="availability" defaultValue={seller.availability}><option>AVAILABLE</option><option>OFFLINE</option></select></label><label>Publish number<select name="whatsappPublic" defaultValue={String(seller.whatsappPublic)}><option value="false">Private</option><option value="true">Visible in app</option></select></label></div><label>Region<input name="region" defaultValue={seller.region ?? seller.country ?? ""} maxLength={80} /></label><fieldset className="check-grid"><legend>Supported packages</legend>{commerce.packages.filter((item) => item.active).map((item) => <label key={item.id}><input type="checkbox" name="packageIds" value={item.id} defaultChecked={seller.packageIds.includes(item.id)} />{item.name}</label>)}</fieldset><label>Change reason<input name="reason" minLength={5} maxLength={500} required /></label><button className="primary-button" type="submit">Save seller</button></form></Card>)}</div> : <Card><EmptyState title="No agency or seller accounts" detail="Create an Agency or Coin Seller account first." /></Card>}</> : null}
    <div className="section-subheading"><h2>Purchase requests</h2><p>Completing a request debits seller inventory, credits the user wallet, writes the ledger, and notifies the app in one transaction.</p></div>
    <Card>{commerce.orders.length ? <div className="table-scroll"><table><thead><tr><th>Order</th><th>User</th><th>Seller</th><th>Package</th><th className="align-right">Coins</th><th>Status</th><th>Created</th>{manageOrders ? <th>Review</th> : null}</tr></thead><tbody>{commerce.orders.map((order) => { const statuses = nextOrderStatuses(order.status); return <tr key={order.id}><td className="mono">{order.publicId}</td><td><b>{order.userName}</b><small className="mono block">{order.userPublicId}</small></td><td>{order.sellerName}</td><td>{order.packageName}</td><td className="align-right">{formatNumber(order.coins)}</td><td><StatusBadge value={order.status} />{order.reviewNote ? <small className="block">{order.reviewNote}</small> : null}</td><td>{formatDate(order.createdAt)}</td>{manageOrders ? <td>{statuses.length ? <form action={submitCoinOrderTransition} className="inline-review"><input type="hidden" name="orderId" value={order.id} /><select name="nextStatus" required defaultValue=""><option value="" disabled>Update…</option>{statuses.map((status) => <option key={status}>{status}</option>)}</select><input name="note" minLength={5} maxLength={500} required placeholder="Review note" /><button className="table-button" type="submit">Save</button></form> : <span className="muted">Final</span>}</td> : null}</tr>; })}</tbody></table></div> : <EmptyState title="No purchase requests" detail="Mobile orders appear after a user selects an active package and approved seller." />}<Pagination path="/dashboard/commerce" page={page} hasNext={rows.orders.length > 25} /></Card>
  </>;
}
