import { Gift, Plus } from "lucide-react";
import { submitCreateGift, submitGiftStatus, submitGiftUpdate } from "@/app/admin-actions";
import { Card, EmptyState, Notice, SectionHeading, StatusBadge } from "@/components/ui";
import { GiftArtworkFields } from "@/components/gift-artwork-fields";
import { can } from "@/lib/auth/permissions";
import { requirePermission } from "@/lib/auth/guard";
import { listGifts } from "@/lib/db/repositories/catalog";
import { formatNumber } from "@/lib/utils/format";

export const dynamic = "force-dynamic";

export default async function GiftsPage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) {
  const scope = await requirePermission("gifts.read"); const { error, success } = await searchParams; const gifts = await listGifts(); const manage = can(scope.account.role, "gifts.manage");
  return <><SectionHeading title="Mall catalogue" description="Manage virtual gifts, entry frames, profile effects, medals and badges from one backend catalogue." action={manage ? <a className="primary-button" href="#new-gift"><Plus size={16} />New item</a> : undefined} />{success ? <Notice type="success">{success}</Notice> : null}{error ? <Notice type="error">{error}</Notice> : null}
    {manage ? <Card className="create-panel"><details id="new-gift"><summary><span><Gift size={18} /><b>Create Mall item</b></span><small>Choose a type and artwork. Virtual gifts remain the only items available in room gifting.</small></summary><form action={submitCreateGift} className="admin-form"><div className="form-grid"><label>Item key<input name="key" required pattern="[a-z0-9_]+" placeholder="premium_gold_frame" /></label><label>Type<select name="catalogType" defaultValue="VIRTUAL_GIFT" required><option value="VIRTUAL_GIFT">Virtual Gift</option><option value="ENTRY_FRAME">Entry Frame</option><option value="PROFILE_EFFECT">Profile Effect</option><option value="MEDAL">Medal</option><option value="BADGE">Badge</option></select></label><label>Name<input name="name" required /></label><label>Category<input name="category" required placeholder="Popular" /></label><label>Coin price<input name="coinPrice" type="number" min="1" required /></label><label>Animation key <span>(optional)</span><input name="animationKey" placeholder="effect.premium_gold" /></label><GiftArtworkFields requireArtwork /></div><div className="form-submit"><p>Only enabled backend items appear in the app. Historic gift transactions keep their price snapshots.</p><button className="primary-button" type="submit">Create item</button></div></form></details></Card> : null}
    <Card>{gifts.length ? <div className="table-scroll"><table><thead><tr><th>Item</th><th>Artwork</th><th>Key</th><th>Type</th><th>Category</th><th className="align-right">Coin price</th><th>Animation</th><th>Status</th>{manage ? <th>Action</th> : null}</tr></thead><tbody>{gifts.map((gift) => <tr key={gift.id}><td><b>{gift.name}</b></td><td><span className="gift-artwork-chip">{gift.emoji ?? (gift.visualUrl ? "Image" : "🎁")}</span></td><td className="mono">{gift.key}</td><td>{gift.catalogType.replaceAll("_", " ")}</td><td>{gift.category}</td><td className="align-right">{formatNumber(gift.coinPrice)}</td><td>{gift.animationKey ?? "—"}</td><td><StatusBadge value={gift.active ? "ACTIVE" : "DISABLED"} /></td>{manage ? <td><div className="account-actions"><details className="row-action gift-edit"><summary>Edit</summary><form action={submitGiftUpdate}><input type="hidden" name="id" value={gift.id} /><label>Name<input name="name" defaultValue={gift.name} required /></label><label>Type<select name="catalogType" defaultValue={gift.catalogType} required><option value="VIRTUAL_GIFT">Virtual Gift</option><option value="ENTRY_FRAME">Entry Frame</option><option value="PROFILE_EFFECT">Profile Effect</option><option value="MEDAL">Medal</option><option value="BADGE">Badge</option></select></label><label>Category<input name="category" defaultValue={gift.category} required /></label><label>Coin price<input name="coinPrice" type="number" min="1" defaultValue={gift.coinPrice} required /></label><label>Animation key<input name="animationKey" defaultValue={gift.animationKey ?? ""} /></label><GiftArtworkFields currentEmoji={gift.emoji} currentImageUrl={gift.visualUrl} /><label>Change reason<input name="reason" required minLength={5} placeholder="Why is this changing?" /></label><button className="secondary-button" type="submit">Save item</button></form></details><form action={submitGiftStatus}><input type="hidden" name="id" value={gift.id} /><input type="hidden" name="active" value={String(!gift.active)} /><button className="table-link button-link" type="submit">{gift.active ? "Disable" : "Enable"}</button></form></div></td> : null}</tr>)}</tbody></table></div> : <EmptyState title="No Mall items configured" detail="Create an item for the backend-controlled mobile catalogue." />}</Card>
  </>;
}
