import { Download, FileSpreadsheet, ShieldCheck, Radio, Gamepad2, Building2, Network, Coins } from "lucide-react";
import Link from "next/link";
import { Card, MetricCard, SectionHeading } from "@/components/ui";
import { requirePermission } from "@/lib/auth/guard";
import { getEconomyMetrics } from "@/lib/db/repositories/dashboard";
import { formatNumber } from "@/lib/utils/format";

export const dynamic = "force-dynamic";

export default async function ReportsPage() {
  const scope = await requirePermission("reports.export");
  const economy = scope.account.role === "MASTER" ? await getEconomyMetrics() : null;
  return <><SectionHeading title="Reports" description="Exports are generated by the server and always respect the signed-in account's hierarchy." />
    {economy ? <Card>
      <div className="card-title"><div><h2>Economy health</h2><p>Auditable lifetime totals from completed ledger entries. Coins remain one balance; Diamonds remain the withdrawal liability.</p></div></div>
      <div className="metric-grid">
        <MetricCard label="Purchased Coins issued" value={`${formatNumber(economy.purchasedCoins)} Coins`} icon={<FileSpreadsheet size={20} />} />
        <MetricCard label="Promotional Coins issued" value={`${formatNumber(economy.promotionalCoins)} Coins`} icon={<FileSpreadsheet size={20} />} />
        <MetricCard label="Game wagers" value={`${formatNumber(economy.gameWagers)} Coins`} icon={<FileSpreadsheet size={20} />} />
        <MetricCard label="Game returns" value={`${formatNumber(economy.gameReturns)} Coins`} icon={<FileSpreadsheet size={20} />} />
        <MetricCard label="Realized game RTP" value={`${(economy.realizedGameRtp * 100).toFixed(2)}%`} icon={<FileSpreadsheet size={20} />} />
        <MetricCard label="Game sink" value={`${formatNumber(economy.gameSink)} Coins`} icon={<FileSpreadsheet size={20} />} />
        <MetricCard label="Gift spending" value={`${formatNumber(economy.giftCoins)} Coins`} icon={<FileSpreadsheet size={20} />} />
        <MetricCard label="Gift earnings" value={`${formatNumber(economy.giftDiamonds)} Diamonds`} icon={<FileSpreadsheet size={20} />} />
        <MetricCard label="Hourly rewards" value={`${formatNumber(economy.hourlyDiamonds)} Diamonds`} icon={<FileSpreadsheet size={20} />} />
        <MetricCard label="Outstanding liability" value={`${formatNumber(economy.outstandingDiamonds)} Diamonds`} icon={<FileSpreadsheet size={20} />} />
        <MetricCard label="Completed withdrawals" value={`${formatNumber(economy.completedWithdrawals)} Diamonds`} icon={<FileSpreadsheet size={20} />} />
      </div>
    </Card> : null}
    <div className="report-grid"><Card><Building2 className="report-icon" size={24} /><h2>Agency Report</h2><p>Authorized Agencies and Hosts, joining dates, current statuses and target-source availability.</p><Link className="primary-button" href="/dashboard/agency-report">Open Agency Report</Link></Card><Card><Network className="report-icon" size={24} /><h2>Hierarchy Report</h2><p>Hierarchy nodes and actual descendant Agency/Host counts, with scoped Excel export.</p><Link className="primary-button" href="/dashboard/hierarchy-report">Open Hierarchy Report</Link></Card><Card><Radio className="report-icon" size={24} /><h2>Live Reward Monitoring</h2><p>One row per durable Live session, with canonical eligible time, rewards, claims and gift totals.</p><Link className="primary-button" href="/dashboard/live-rewards">Open Live Reward Monitoring</Link></Card><Card><Gamepad2 className="report-icon" size={24} /><h2>Game Management</h2><p>COIN balances and completed game rounds from the authoritative result records.</p><Link className="primary-button" href="/dashboard/game-management">Open Game Management</Link></Card><Card><Coins className="report-icon" size={24} /><h2>Coin Transfer History</h2><p>Seller-private transfers with Last 24 Hours and Date Wise filters. Coin Seller permission required.</p><Link className="primary-button" href="/dashboard/coin-transfers">Open Transfer History</Link></Card><Card><FileSpreadsheet className="report-icon" size={24} /><h2>Ledger transactions</h2><p>Existing completed financial records with codes, sources, destinations, amounts and timestamps.</p><Link className="primary-button" href="/api/reports/transactions"><Download size={16} />Download CSV</Link></Card><Card><ShieldCheck className="report-icon" size={24} /><h2>Safe by design</h2><p>Report data is generated server-side from canonical records and constrained by the signed-in account’s authorization scope.</p><span className="scope-lock">Scope applied automatically</span></Card></div>
  </>;
}
