import { Download, FileSpreadsheet, ShieldCheck } from "lucide-react";
import { Card, SectionHeading } from "@/components/ui";
import { requirePermission } from "@/lib/auth/guard";

export const dynamic = "force-dynamic";

export default async function ReportsPage() {
  await requirePermission("reports.export");
  return <><SectionHeading title="Reports" description="Exports are generated by the server and always respect the signed-in account's hierarchy." />
    <div className="report-grid"><Card><FileSpreadsheet className="report-icon" size={24} /><h2>Ledger transactions</h2><p>Completed financial records with codes, sources, destinations, amounts, and timestamps.</p><a className="primary-button" href="/api/reports/transactions"><Download size={16} />Download CSV</a></Card><Card><ShieldCheck className="report-icon" size={24} /><h2>Safe by design</h2><p>Cells that could be interpreted as spreadsheet formulas are escaped before download. Payout destinations remain masked.</p><span className="scope-lock">Scope applied automatically</span></Card></div>
  </>;
}
