import { Download, FileSpreadsheet, ShieldCheck } from "lucide-react";
import { Card, MetricCard, SectionHeading } from "@/components/ui";
import { requirePermission } from "@/lib/auth/guard";
import { getEconomyMetrics } from "@/lib/db/repositories/dashboard";
import { formatNumber } from "@/lib/utils/format";

export const dynamic = "force-dynamic";

export default async function ReportsPage() {
  const scope = await requirePermission("reports.export");
  const economy = scope.account.role === "MASTER" ? await getEconomyMetrics() : null;
  return <><SectionHeading title="Reports" description="Exports are generated by the server and always respect the signed-in account's hierarchy." />
    {economy ? <Card>
      <div className="card-title"><div><h2>Economy health</h2><p>Auditable lifetime totals from completed ledger entries. Coins remain one balance; Diamonds remain the withdrawal liability.</p></div></div>
      <div className="metric-grid">
        <MetricCard label="Purchased Coins issued" value={`${formatNumber(economy.purchasedCoins)} Coins`} icon={<FileSpreadsheet size={20} />} />
        <MetricCard label="Promotional Coins issued" value={`${formatNumber(economy.promotionalCoins)} Coins`} icon={<FileSpreadsheet size={20} />} />
        <MetricCard label="Game wagers" value={`${formatNumber(economy.gameWagers)} Coins`} icon={<FileSpreadsheet size={20} />} />
        <MetricCard label="Game returns" value={`${formatNumber(economy.gameReturns)} Coins`} icon={<FileSpreadsheet size={20} />} />
        <MetricCard label="Realized game RTP" value={`${(economy.realizedGameRtp * 100).toFixed(2)}%`} icon={<FileSpreadsheet size={20} />} />
        <MetricCard label="Game sink" value={`${formatNumber(economy.gameSink)} Coins`} icon={<FileSpreadsheet size={20} />} />
        <MetricCard label="Gift spending" value={`${formatNumber(economy.giftCoins)} Coins`} icon={<FileSpreadsheet size={20} />} />
        <MetricCard label="Gift earnings" value={`${formatNumber(economy.giftDiamonds)} Diamonds`} icon={<FileSpreadsheet size={20} />} />
        <MetricCard label="Hourly rewards" value={`${formatNumber(economy.hourlyDiamonds)} Diamonds`} icon={<FileSpreadsheet size={20} />} />
        <MetricCard label="Outstanding liability" value={`${formatNumber(economy.outstandingDiamonds)} Diamonds`} icon={<FileSpreadsheet size={20} />} />
        <MetricCard label="Completed withdrawals" value={`${formatNumber(economy.completedWithdrawals)} Diamonds`} icon={<FileSpreadsheet size={20} />} />
      </div>
    </Card> : null}
    <div className="report-grid"><Card><FileSpreadsheet className="report-icon" size={24} /><h2>Ledger transactions</h2><p>Completed financial records with codes, sources, destinations, amounts, and timestamps.</p><a className="primary-button" href="/api/reports/transactions"><Download size={16} />Download CSV</a></Card><Card><ShieldCheck className="report-icon" size={24} /><h2>Safe by design</h2><p>Cells that could be interpreted as spreadsheet formulas are escaped before download. Payout destinations remain masked.</p><span className="scope-lock">Scope applied automatically</span></Card></div>
  </>;
}
