import { randomUUID } from "crypto";
import Image from "next/image";
import { Coins, Search, Send, UserRound } from "lucide-react";
import { submitCoinInventoryAdjustment, submitCoinTransfer, submitPlatformCoinAllocation } from "@/app/actions";
import { Card, EmptyState, Notice, SectionHeading, StatusBadge } from "@/components/ui";
import { can } from "@/lib/auth/permissions";
import { requirePermission } from "@/lib/auth/guard";
import { getRecentLedger } from "@/lib/db/repositories/dashboard";
import { listPlatformAccounts } from "@/lib/db/repositories/administration";
import { searchCoinTransferRecipients } from "@/lib/db/repositories/directory";
import { formatDate, formatNumber } from "@/lib/utils/format";
import { countryName } from "@/lib/countries";

export const dynamic = "force-dynamic";

export default async function WalletPage({ searchParams }: { searchParams: Promise<{ q?: string; error?: string; success?: string }> }) {
  const scope = await requirePermission("wallet.read");
  const { q = "", error, success } = await searchParams;
  const canAllocate = can(scope.account.role, "coins.allocate");
  const allowed = can(scope.account.role, "coins.transfer");
  const [users, ledger, accounts] = await Promise.all([allowed ? searchCoinTransferRecipients(scope, q) : Promise.resolve([]), getRecentLedger(scope), canAllocate ? listPlatformAccounts(scope) : Promise.resolve([])]);
  const idempotencyKey = randomUUID();
  const mintKey = randomUUID();
  const allocationKey = randomUUID();
  const inventoryAccounts = accounts.filter((account) => account.id !== scope.account.id && account.role !== "MASTER" && account.status === "ACTIVE");
  return <>
    <SectionHeading title="Wallet & economy" description="Balances are snapshots. The immutable ledger is the financial source of truth." />
    {success ? <Notice type="success">{success}</Notice> : null}{error ? <Notice type="error">{error}</Notice> : null}
    <div className="split-grid">
      <Card className="transfer-card"><div className="card-title"><div><h2>Coin transfer</h2><p>Moves allocated inventory to one valid application user.</p></div><Coins size={20} /></div>
        {allowed ? <><form className="filter-bar" action="/dashboard/wallet"><label className="search-field"><Search size={17} /><input name="q" defaultValue={q} required maxLength={120} placeholder="Search any user by ID, name, or phone" autoFocus /><button className="secondary-button" type="submit">Find user</button></label><span>All active Nazraa users</span></form>{q && !users.length ? <EmptyState title="No active user found" detail="Check the User/Host ID, name, or phone and try again." /> : null}{users.length ? <form action={submitCoinTransfer} className="stack-form"><input type="hidden" name="idempotencyKey" value={idempotencyKey} /><fieldset className="recipient-picker"><legend>Confirm recipient</legend>{users.map((user) => <label className="recipient-card" key={user.id}><input type="radio" name="recipientId" value={user.id} required /><span className="recipient-avatar">{user.avatarUrl ? <Image src={user.avatarUrl} alt="" width={44} height={44} unoptimized /> : <UserRound size={22} />}</span><span className="recipient-identity"><b>{user.fullName}</b><small>User ID {user.publicId} · Host ID {user.externalUserId}</small><small>{countryName(user.countryCode)}{user.agencyName ? ` · ${user.agencyName}` : " · Unassigned"}</small></span><span className="recipient-balance">{formatNumber(user.coins)} coins</span></label>)}</fieldset><div className="two-fields"><label>Coins<input name="amount" inputMode="numeric" type="number" min="1" placeholder="e.g. 5000" required /></label><label>Reason<input name="reason" minLength={5} maxLength={500} placeholder="Sale or transfer reference" required /></label></div><label className="checkbox-line"><input type="checkbox" name="confirmed" value="yes" required />Confirm this coin transfer</label><button className="primary-button" type="submit"><Send size={16} />Send coins</button><p className="form-note">The server locks both wallets, checks inventory, writes paired ledger entries, and prevents duplicate transfers.</p></form> : !q ? <p className="quiet-empty">Search a user by name, ID, or phone to begin.</p> : null}</> : <EmptyState title="Transfers are not available" detail="Your role can view its economy records but cannot move coin inventory." />}
      </Card>
      <Card><div className="card-title"><div><h2>Transfer safeguards</h2><p>Small set of rules that keeps money operations dependable.</p></div></div><ul className="rule-list"><li>Authorized operators can recharge any active Nazraa user found by search.</li><li>Whole positive coin amounts only.</li><li>Insufficient inventory stops the transfer.</li><li>Every change creates paired ledger records.</li><li>A reason and audit record are mandatory.</li></ul></Card>
    </div>
    {can(scope.account.role, "coins.mint") ? <Card className="inventory-card"><div className="card-title"><div><h2>Generate platform coins</h2><p>Master-only. Coins are generated into the Master wallet before distribution.</p></div></div><form action={submitCoinInventoryAdjustment} className="form-grid"><input type="hidden" name="idempotencyKey" value={mintKey} /><input type="hidden" name="accountId" value={scope.account.id} /><label>Action<select name="direction" defaultValue="ADD"><option value="ADD">Generate coins</option><option value="REMOVE">Remove unused coins</option></select></label><label>Coins<input name="amount" type="number" inputMode="numeric" min="1" required /></label><label>Reason<input name="reason" minLength={5} maxLength={500} required placeholder="Reason for supply change" /></label><label className="checkbox-line"><input type="checkbox" name="confirmed" value="yes" required />Confirm supply change</label><label>Finish<button className="primary-button" type="submit">Update platform inventory</button></label></form></Card> : null}
    {canAllocate ? <Card className="inventory-card"><div className="card-title"><div><h2>Distribute available inventory</h2><p>Moves coins from your wallet to an account below you. It never creates new coins.</p></div></div><form action={submitPlatformCoinAllocation} className="form-grid"><input type="hidden" name="idempotencyKey" value={allocationKey} /><label>Downstream account<select name="accountId" required defaultValue=""><option value="" disabled>Select account</option>{inventoryAccounts.map((account) => <option value={account.id} key={account.id}>{account.displayRole} · {account.name} · {account.code}</option>)}</select></label><label>Coins<input name="amount" type="number" inputMode="numeric" min="1" required /></label><label className="span-two">Reason<input name="reason" minLength={5} maxLength={500} required placeholder="Why is this allocation needed?" /></label><label className="checkbox-line"><input type="checkbox" name="confirmed" value="yes" required />Confirm allocation</label><label>Finish<button className="primary-button" type="submit">Allocate from my inventory</button></label></form></Card> : null}
    <Card><div className="card-title"><div><h2>Recent ledger activity</h2><p>Latest financial records visible to your role.</p></div></div>{ledger.length ? <div className="table-scroll"><table><thead><tr><th>Code</th><th>Type</th><th>Destination</th><th className="align-right">Amount</th><th>Status</th><th>Recorded</th></tr></thead><tbody>{ledger.map((entry) => <tr key={entry.id}><td className="mono">{entry.transactionCode}</td><td>{entry.transactionType.replaceAll("_", " ")}</td><td>{entry.destinationName}</td><td className="align-right">{formatNumber(entry.amount)} {entry.assetType.toLowerCase()}s</td><td><StatusBadge value={entry.status} /></td><td>{formatDate(entry.createdAt)}</td></tr>)}</tbody></table></div> : <p className="quiet-empty">No finance records yet.</p>}</Card>
  </>;
}
