import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import type { Connection, RowDataPacket } from "mysql2/promise";
import type { MobileIdentity } from "@/lib/auth/mobile-session";

export async function verifyFaceLiveMaster(root: Connection, makeUser: (name: string) => Promise<MobileIdentity>, owner: MobileIdentity) {
  const product = await import("@/lib/db/repositories/mobile-product");
  const rooms = await import("@/lib/db/repositories/mobile-completion");
  const social = await import("@/lib/db/repositories/face-live-social");
  const liveRules = await import("@/lib/services/live-business-policy");
  const giftId = 'qa_rose';
  const create = async (host: MobileIdentity) => {
    const id = randomUUID(), session = randomUUID(), roomCode = `FM${randomUUID().slice(0,8)}`;
    await root.execute("INSERT INTO live_rooms (id, room_code, host_application_user_id, room_type, title, status) VALUES (?, ?, ?, 'FACE', 'Isolated Face QA', 'ACTIVE')", [id, roomCode, host.userId]);
    await root.execute("INSERT INTO live_session_accounting (id, room_id, host_application_user_id, room_type, started_at) VALUES (?, ?, ?, 'FACE', CURRENT_TIMESTAMP(3))", [session,id,host.userId]);
    await root.execute("INSERT INTO live_room_members (room_id, application_user_id, room_role, media_role, muted) VALUES (?, ?, 'OWNER','HOST',FALSE)", [id,host.userId]);
    return {id,session,roomCode};
  };
  const host = await makeUser('Face Master Host');
  const room = await create(host);
  const users = await Promise.all(Array.from({length:7},(_,i)=>makeUser(`Face QA ${i}`)));
  for (const user of users) await rooms.joinLiveRoom(user,room.roomCode);
  const state = async () => social.faceLiveSocial(host,room.roomCode);
  assert.equal((await state()).sessionDiamonds,0);
  for (const user of users.slice(0,4)) await rooms.requestLiveCoHost(user,room.roomCode);
  for (const user of users.slice(0,2)) await rooms.respondLiveCoHost(host,{roomCode:room.roomCode,targetPublicId:user.publicId,accept:true});
  const race = await Promise.allSettled(users.slice(2,4).map(user=>rooms.respondLiveCoHost(host,{roomCode:room.roomCode,targetPublicId:user.publicId,accept:true})));
  assert.equal(race.filter(result=>result.status==='fulfilled').length,1,'one final seat only');
  const [seats] = await root.query<RowDataPacket[]>("SELECT * FROM live_room_members WHERE room_id = ? AND media_role = 'AUDIO_GUEST' AND left_at IS NULL",[room.id]);
  assert.equal(seats.length,3);
  assert.ok(seats.every(seat=>seat.seat_session_id && seat.seat_version > 0));
  const sender=users[6];
  const intent={clientGiftId:randomUUID(),roomCode:room.roomCode,giftId,recipientPublicId:'0',recipientMode:'ALL' as const,quantity:2};
  const [before]=await root.query<RowDataPacket[]>("SELECT available_balance FROM wallet_balances WHERE owner_id=? AND asset_type='COIN'",[sender.userId]);
  const results=await Promise.all([product.sendGift(sender,intent),product.sendGift(sender,intent)]);
  assert.equal(results.filter(r=>!r.replayed).length,1);
  const committed=results.find(r=>!r.replayed)!;
  assert.equal(committed.events.length,4);
  assert.equal(committed.totalCoins,400);
  const [after]=await root.query<RowDataPacket[]>("SELECT available_balance FROM wallet_balances WHERE owner_id=? AND asset_type='COIN'",[sender.userId]);
  assert.equal(Number(before[0].available_balance)-Number(after[0].available_balance),400);
  assert.equal((await state()).sessionDiamonds,97,'only Host credit is session total');
  await assert.rejects(product.sendGift(sender,{...intent,clientGiftId:randomUUID(),recipientMode:'SINGLE',recipientPublicId:users[5].publicId}));
  await assert.rejects(product.sendGift(sender,{...intent,quantity:3}),'same ID cannot change intent');
  await root.execute("UPDATE wallet_balances SET available_balance=1 WHERE owner_id=? AND asset_type='COIN'",[sender.userId]);
  const [eventBefore]=await root.query<RowDataPacket[]>("SELECT COUNT(*) count FROM live_room_gift_events WHERE room_id=?",[room.id]);
  await assert.rejects(product.sendGift(sender,{...intent,clientGiftId:randomUUID()}));
  const [eventAfter]=await root.query<RowDataPacket[]>("SELECT COUNT(*) count FROM live_room_gift_events WHERE room_id=?",[room.id]);
  assert.equal(eventBefore[0].count,eventAfter[0].count,'ALL failure rolls back every recipient');
  for (const [index,user] of users.slice(0,6).entries()) await product.sendGift(user,{clientGiftId:randomUUID(),roomCode:room.roomCode,giftId,recipientPublicId:host.publicId,quantity:index+1});
  let current=await state();
  const daily=current.daily as {user:{id:string};diamonds:number}[];
  assert.equal(daily.length,5);
  assert.equal(daily[0].user.id,users[5].publicId);
  assert.equal(current.topFanId,users[5].publicId);
  assert.equal(current.sessionDiamonds,97+users.slice(0,6).reduce((sum,_,i)=>sum+product.giftDiamondValue(50*(i+1)),0));
  const rules=await liveRules.loadFaceLiveRules(root);
  const day=liveRules.businessDateFor(rules.timezone);
  // Repository-only clock injection proves boundaries regardless of the day
  // this test runs. No API accepts a client-selected business date.
  await root.execute("UPDATE live_room_gift_events SET business_date='2026-10-15' WHERE room_id=?",[room.id]);
  await root.execute("UPDATE live_room_gift_events SET business_date='2026-10-01' WHERE room_id=? AND sender_application_user_id=?",[room.id,users[5].userId]);
  current=await social.faceLiveSocial(host,room.roomCode,new Date('2026-10-15T12:00:00Z'));
  assert.notEqual((current.daily as typeof daily)[0].user.id,users[5].publicId);
  assert.equal((current.monthly as typeof daily)[0].user.id,users[5].publicId,'monthly contributions differ from today');
  const rollover=await social.faceLiveSocial(host,room.roomCode,new Date('2026-11-01T12:00:00Z'));
  assert.equal((rollover.monthly as unknown[]).length,0,'new month is empty, not previous Top Fan');
  assert.equal(rollover.topFanId,null);
  assert.equal(rollover.sessionDiamonds,current.sessionDiamonds,'monthly rollover does not reset active session');
  await root.execute("UPDATE live_room_gift_events SET business_date=? WHERE room_id=?",[day,room.id]);
  await rooms.setRoomAdmin(host,{roomCode:room.roomCode,targetPublicId:users[4].publicId,makeAdmin:true});
  await assert.rejects(rooms.respondLiveCoHost(users[4],{roomCode:room.roomCode,targetPublicId:users[3].publicId,accept:true}));
  await assert.rejects(rooms.respondLiveCoHost(users[4],{roomCode:room.roomCode,targetPublicId:users[3].publicId,accept:false}));
  const seated=users.find(user=>user.userId===seats[0].application_user_id)!;
  await rooms.endLiveCoHost(users[4],{roomCode:room.roomCode,targetPublicId:seated.publicId});
  const [released]=await root.query<RowDataPacket[]>("SELECT * FROM live_room_members WHERE room_id=? AND application_user_id=?",[room.id,seated.userId]);
  assert.equal(released[0].room_role,'AUDIENCE');
  assert.equal(released[0].left_at,null);
  assert.equal(released[0].seat_session_id,null);
  const remaining=seats.filter(seat=>seat.application_user_id!==seated.userId);
  await root.execute("UPDATE live_room_members SET media_publishing=FALSE, last_seen_at=TIMESTAMPADD(MINUTE,-10,CURRENT_TIMESTAMP(3)), last_media_heartbeat_at=TIMESTAMPADD(MINUTE,-10,CURRENT_TIMESTAMP(3)) WHERE room_id=? AND application_user_id=?",[room.id,remaining[0].application_user_id]);
  await root.execute("UPDATE live_room_members SET media_publishing=FALSE, last_seen_at=TIMESTAMPADD(MINUTE,-10,CURRENT_TIMESTAMP(3)), last_media_heartbeat_at=CURRENT_TIMESTAMP(3) WHERE room_id=? AND application_user_id=?",[room.id,remaining[1].application_user_id]);
  const cleanup=await rooms.pruneDisconnectedFaceGuests();
  assert.equal(cleanup.find(value=>value.roomCode===room.roomCode)?.publicIds.length,1,'only expired Guest is removed');
  const [survivor]=await root.query<RowDataPacket[]>("SELECT seat_session_id FROM live_room_members WHERE room_id=? AND application_user_id=?",[room.id,remaining[1].application_user_id]);
  assert.equal(survivor[0].seat_session_id,remaining[1].seat_session_id,'short reconnect preserves seat identity');
  assert.equal((await rooms.pruneDisconnectedFaceGuests()).length,0,'cleanup is idempotent');
  const preserved=(await state()).sessionDiamonds;
  await rooms.joinLiveRoom(sender,room.roomCode);
  assert.equal((await state()).sessionDiamonds,preserved,'rejoin does not reset gifts');
  const next=await create(host);
  await rooms.joinLiveRoom(users[4],next.roomCode);
  const nextState=await social.faceLiveSocial(host,next.roomCode);
  assert.equal(nextState.sessionDiamonds,0,'new session starts zero');
  assert.ok((nextState.adminIds as string[]).includes(users[4].publicId),'Host Admin persists across rooms');
  await rooms.setRoomAdmin(host,{roomCode:next.roomCode,targetPublicId:users[4].publicId,makeAdmin:false});
  assert.equal(((await social.faceLiveSocial(host,next.roomCode)).adminIds as string[]).length,0);
  const other=await create(owner);
  assert.equal(((await social.faceLiveSocial(owner,other.roomCode)).monthly as unknown[]).length,0,'no cross-Host rankings');
  console.log('PASS Face master: three-seat race, durable seat release, Single/ALL atomic gifts, concurrent idempotency, rollback, session zero/rejoin/reset, exact Top5, monthly Top Fan, persistent Host Admin and Host-only call authority');
}
