#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLATFORM_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$(mktemp "${TMPDIR:-/tmp}/nazraa-production-env.XXXXXX")"

cleanup() {
  rm -f "$ENV_FILE"
}
trap cleanup EXIT

cd "$PLATFORM_DIR"
echo "Pulling encrypted production environment from Vercel..."
npx vercel env pull "$ENV_FILE" --environment=production --yes

set -a
# The file is generated by Vercel for this linked Nazraa project.
source "$ENV_FILE"
set +a

npm run typecheck
npm run lint
npm run build
echo "Applying pending production database migrations..."
npm run migrate
echo "Deploying the verified Control Platform build..."
npx vercel deploy --prod --yes
