import { Ban, Radio } from "lucide-react";
import { submitTemporaryRestriction } from "@/app/actions";
import { submitRestoreLiveAccess, submitRoomStatus } from "@/app/admin-actions";
import { Card, EmptyState, Notice, SectionHeading, StatusBadge } from "@/components/ui";
import { can } from "@/lib/auth/permissions";
import { requirePermission } from "@/lib/auth/guard";
import { listPresenceIncidents, listRooms } from "@/lib/db/repositories/operations";
import { formatDate, formatNumber } from "@/lib/utils/format";

export const dynamic = "force-dynamic";

export default async function RoomsPage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) {
  const scope = await requirePermission("rooms.read");
  const { error, success } = await searchParams;
  const [rooms, incidents] = await Promise.all([listRooms(scope), listPresenceIncidents(scope)]);
  const mayRestrict = can(scope.account.role, "rooms.restrict");
  const mayManage = can(scope.account.role, "rooms.manage");
  return <><SectionHeading title="Live rooms" description="Monitoring refreshes from the room backend. Controls are deliberately limited and always auditable." />
    {success ? <Notice type="success">{success}</Notice> : null}{error ? <Notice type="error">{error}</Notice> : null}
    <Card>{rooms.length ? <div className="table-scroll"><table><thead><tr><th>Room</th><th>Host</th><th>Type</th><th>Room tools</th><th className="align-right">Audience</th><th>Started</th><th>Status</th>{mayRestrict || mayManage ? <th>Moderation</th> : null}</tr></thead><tbody>{rooms.map((room) => <tr key={room.id}><td className="mono">{room.roomCode}</td><td><b>{room.hostName}</b><small className="mono block">{room.hostExternalId}</small></td><td>{room.roomType}</td><td><small className="block">{room.themeEnabled ? `Theme ${room.themeIndex + 1}` : "Theme off"} · {room.passwordProtected ? "Password" : "Open"} · {room.chatLocked ? "Chat locked" : "Chat open"}</small><small className="block">PK {room.pkRequestsEnabled ? `${room.pkCount} · requests on` : "requests off"} · Presence incidents {room.presenceIncidents}</small></td><td className="align-right">{formatNumber(room.audience)}</td><td>{formatDate(room.startedAt)}</td><td><StatusBadge value={room.status} /></td>{mayRestrict || mayManage ? <td><div className="room-actions">{mayRestrict && room.status !== "ENDED" ? <details className="moderation"><summary><Ban size={14} />Restrict host</summary><form action={submitTemporaryRestriction}><input type="hidden" name="applicationUserId" value={room.applicationUserId} /><input name="reason" minLength={5} maxLength={500} required placeholder="Reason is required" /><button className="danger-button" type="submit">2-hour restriction</button></form></details> : null}{mayManage && room.status !== "ENDED" ? <details className="moderation"><summary>Room action</summary><form action={submitRoomStatus}><input type="hidden" name="roomId" value={room.id} /><select name="status" required defaultValue=""><option value="" disabled>Choose</option>{room.status === "LOCKED" ? <option value="ACTIVE">Unlock room</option> : <option value="LOCKED">Lock room</option>}<option value="ENDED">End room</option></select><input name="reason" minLength={5} required placeholder="Reason" /><button className="danger-button" type="submit">Confirm</button></form></details> : null}</div></td> : null}</tr>)}</tbody></table></div> : <EmptyState title="No rooms active or recently recorded" detail="Room monitoring becomes available as the live backend sends room events." />}</Card>
    <div className="section-subheading"><h2>Camera-presence history</h2><p>Only numeric on-device detection results are recorded. No camera image is uploaded or retained.</p></div>
    <Card>{incidents.length ? <div className="table-scroll"><table><thead><tr><th>Host</th><th>Room</th><th>Event</th><th>Failures</th><th>Time</th><th>Live access</th></tr></thead><tbody>{incidents.map((incident) => <tr key={incident.id}><td><b>{incident.userName}</b><small className="mono block">{incident.userPublicId}</small></td><td><span className="mono">{incident.roomCode}</span><small className="block">{incident.roomType}</small></td><td><StatusBadge value={incident.incidentType} /></td><td>{incident.consecutiveFailures}</td><td>{formatDate(incident.createdAt)}</td><td>{incident.restrictionId ? mayManage ? <details className="row-action"><summary>Suspended · review</summary><form action={submitRestoreLiveAccess}><input type="hidden" name="restrictionId" value={incident.restrictionId} /><input name="reason" minLength={5} maxLength={500} required placeholder="Restoration reason" /><button className="secondary-button" type="submit">Restore Live access</button></form></details> : <StatusBadge value="SUSPENDED" /> : <StatusBadge value="ACTIVE" />}</td></tr>)}</tbody></table></div> : <EmptyState title="No camera-presence incidents" detail="Automatic Live stops will be listed here for authorized staff review." />}</Card>
    <p className="footnote"><Radio size={14} />Monitoring/CS can apply a server-computed two-hour live restriction. This screen does not offer permanent bans.</p>
  </>;
}
