import Link from "next/link";
import { FileLock2, Plus, UserCog } from "lucide-react";
import { submitAccountStatus, submitCreateAccount, submitPasswordReset } from "@/app/admin-actions";
import { Card, EmptyState, Notice, SectionHeading, StatusBadge } from "@/components/ui";
import { can } from "@/lib/auth/permissions";
import { requirePermission } from "@/lib/auth/guard";
import { listParentOptions, listPlatformAccounts, rolesCreatableBy } from "@/lib/db/repositories/administration";
import { formatDate } from "@/lib/utils/format";

export const dynamic = "force-dynamic";

export default async function AccountsPage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) {
  const scope = await requirePermission("accounts.read");
  const { error, success } = await searchParams;
  const [accounts, parents] = await Promise.all([listPlatformAccounts(scope), listParentOptions(scope)]);
  const creatable = rolesCreatableBy(scope.account.role);
  const accountTypes = creatable.flatMap((role) => role === "ADMIN" ? ["ADMIN", "BD"] : [role]);
  const canCreate = can(scope.account.role, "accounts.create") && creatable.length > 0;
  const canManage = can(scope.account.role, "accounts.manage");
  return <>
    <SectionHeading title="Team accounts" description="Create panel logins here. Ordinary Nazraa users still register in the mobile app." action={canCreate ? <a className="primary-button" href="#create-account"><Plus size={16} />Create account</a> : undefined} />
    {success ? <Notice type="success">{success}</Notice> : null}{error ? <Notice type="error">{error}</Notice> : null}
    {canCreate ? <Card className="create-panel"><details id="create-account"><summary><span><UserCog size={18} /><b>Create a panel account</b></span><small>Super Admin, Admin, BD, Agency, Seller, or Monitoring</small></summary><form action={submitCreateAccount} className="admin-form" encType="multipart/form-data"><div className="form-grid"><label>Account type<select name="accountType" required defaultValue=""><option value="" disabled>Select role</option>{accountTypes.map((role) => <option value={role} key={role}>{role.replaceAll("_", " ")}</option>)}</select></label><label>Full name<input name="fullName" required maxLength={120} /></label><label>Country code<input name="countryCode" required minLength={2} maxLength={2} placeholder="IN" /></label><label>Mobile<input name="mobile" inputMode="tel" placeholder="+919876543210" /></label><label>Email<input name="email" type="email" /></label><label>Existing app user ID <span>(optional)</span><input name="applicationUserId" /></label><label>Parent account <span>(required for Admin/BD or Agency)</span><select name="requestedParentId" defaultValue=""><option value="">Automatic when allowed</option>{parents.map((parent) => <option value={parent.id} key={parent.id}>{parent.displayRole} · {parent.name} · {parent.code}</option>)}</select></label><label>Temporary password<input name="password" type="password" required minLength={8} autoComplete="new-password" /></label><label>ID front <span>(JPG, PNG, PDF; 2 MB)</span><input name="idFront" type="file" accept="image/jpeg,image/png,application/pdf" /></label><label>ID back <span>(if applicable)</span><input name="idBack" type="file" accept="image/jpeg,image/png,application/pdf" /></label><label>Profile photo<input name="profilePhoto" type="file" accept="image/jpeg,image/png" /></label></div><div className="form-submit"><p><FileLock2 size={15} />Documents are encrypted before storage and never receive a public URL.</p><button className="primary-button" type="submit">Create account</button></div></form></details></Card> : null}
    <Card>{accounts.length ? <div className="table-scroll"><table><thead><tr><th>Account</th><th>Management ID</th><th>Role</th><th>Parent</th><th>Country</th><th>Documents</th><th>Last login</th><th>Status</th>{canManage ? <th>Manage</th> : null}</tr></thead><tbody>{accounts.map((account) => <tr key={account.id}><td><Link className="table-link" href={`/dashboard/accounts/${account.id}`}><b>{account.name}</b></Link><small className="block">{account.email ?? account.mobile ?? "No contact"}</small></td><td className="mono">{account.code}</td><td>{account.displayRole}</td><td>{account.parentName ?? "Platform root"}</td><td>{account.country ?? "—"}</td><td>{account.documentCount}</td><td>{formatDate(account.lastLoginAt)}</td><td><StatusBadge value={account.status} /></td>{canManage ? <td>{account.role !== "MASTER" && account.id !== scope.account.id ? <div className="account-actions"><details className="row-action"><summary>Status</summary><form action={submitAccountStatus}><input type="hidden" name="accountId" value={account.id} /><select name="nextStatus" required defaultValue=""><option value="" disabled>Status</option><option value="ACTIVE">Active</option><option value="SUSPENDED">Suspended</option><option value="DISABLED">Disabled</option></select><input name="reason" required minLength={5} placeholder="Reason" /><button type="submit" className="secondary-button">Save</button></form></details><details className="row-action"><summary>Password</summary><form action={submitPasswordReset}><input type="hidden" name="accountId" value={account.id} /><input name="password" type="password" minLength={8} required placeholder="Temporary password" /><input name="reason" required minLength={5} placeholder="Reason" /><button type="submit" className="secondary-button">Reset</button></form></details></div> : "—"}</td> : null}</tr>)}</tbody></table></div> : <EmptyState title="No team accounts" detail="Create the first account allowed by your role." />}</Card>
  </>;
}
